//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPSPublicV2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tckimlik.nvi.gov.tr/WS", ConfigurationName="KPSPublicV2.KPSPublicV2Soap")]
    public interface KPSPublicV2Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tckimlik.nvi.gov.tr/WS/KisiVeCuzdanDogrula", ReplyAction="*")]
        System.Threading.Tasks.Task<KPSPublicV2.KisiVeCuzdanDogrulaResponse> KisiVeCuzdanDogrulaAsync(KPSPublicV2.KisiVeCuzdanDogrulaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KisiVeCuzdanDogrulaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KisiVeCuzdanDogrula", Namespace="http://tckimlik.nvi.gov.tr/WS", Order=0)]
        public KPSPublicV2.KisiVeCuzdanDogrulaRequestBody Body;
        
        public KisiVeCuzdanDogrulaRequest()
        {
        }
        
        public KisiVeCuzdanDogrulaRequest(KPSPublicV2.KisiVeCuzdanDogrulaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tckimlik.nvi.gov.tr/WS")]
    public partial class KisiVeCuzdanDogrulaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long TCKimlikNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Soyad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool SoyadYok;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> DogumGun;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool DogumGunYok;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<int> DogumAy;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool DogumAyYok;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int DogumYil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CuzdanSeri;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Nullable<int> CuzdanNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string TCKKSeriNo;
        
        public KisiVeCuzdanDogrulaRequestBody()
        {
        }
        
        public KisiVeCuzdanDogrulaRequestBody(long TCKimlikNo, string Ad, string Soyad, bool SoyadYok, System.Nullable<int> DogumGun, bool DogumGunYok, System.Nullable<int> DogumAy, bool DogumAyYok, int DogumYil, string CuzdanSeri, System.Nullable<int> CuzdanNo, string TCKKSeriNo)
        {
            this.TCKimlikNo = TCKimlikNo;
            this.Ad = Ad;
            this.Soyad = Soyad;
            this.SoyadYok = SoyadYok;
            this.DogumGun = DogumGun;
            this.DogumGunYok = DogumGunYok;
            this.DogumAy = DogumAy;
            this.DogumAyYok = DogumAyYok;
            this.DogumYil = DogumYil;
            this.CuzdanSeri = CuzdanSeri;
            this.CuzdanNo = CuzdanNo;
            this.TCKKSeriNo = TCKKSeriNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KisiVeCuzdanDogrulaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KisiVeCuzdanDogrulaResponse", Namespace="http://tckimlik.nvi.gov.tr/WS", Order=0)]
        public KPSPublicV2.KisiVeCuzdanDogrulaResponseBody Body;
        
        public KisiVeCuzdanDogrulaResponse()
        {
        }
        
        public KisiVeCuzdanDogrulaResponse(KPSPublicV2.KisiVeCuzdanDogrulaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tckimlik.nvi.gov.tr/WS")]
    public partial class KisiVeCuzdanDogrulaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool KisiVeCuzdanDogrulaResult;
        
        public KisiVeCuzdanDogrulaResponseBody()
        {
        }
        
        public KisiVeCuzdanDogrulaResponseBody(bool KisiVeCuzdanDogrulaResult)
        {
            this.KisiVeCuzdanDogrulaResult = KisiVeCuzdanDogrulaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface KPSPublicV2SoapChannel : KPSPublicV2.KPSPublicV2Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class KPSPublicV2SoapClient : System.ServiceModel.ClientBase<KPSPublicV2.KPSPublicV2Soap>, KPSPublicV2.KPSPublicV2Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KPSPublicV2SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(KPSPublicV2SoapClient.GetBindingForEndpoint(endpointConfiguration), KPSPublicV2SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KPSPublicV2SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KPSPublicV2SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KPSPublicV2SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KPSPublicV2SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KPSPublicV2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KPSPublicV2.KisiVeCuzdanDogrulaResponse> KPSPublicV2.KPSPublicV2Soap.KisiVeCuzdanDogrulaAsync(KPSPublicV2.KisiVeCuzdanDogrulaRequest request)
        {
            return base.Channel.KisiVeCuzdanDogrulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<KPSPublicV2.KisiVeCuzdanDogrulaResponse> KisiVeCuzdanDogrulaAsync(long TCKimlikNo, string Ad, string Soyad, bool SoyadYok, System.Nullable<int> DogumGun, bool DogumGunYok, System.Nullable<int> DogumAy, bool DogumAyYok, int DogumYil, string CuzdanSeri, System.Nullable<int> CuzdanNo, string TCKKSeriNo)
        {
            KPSPublicV2.KisiVeCuzdanDogrulaRequest inValue = new KPSPublicV2.KisiVeCuzdanDogrulaRequest();
            inValue.Body = new KPSPublicV2.KisiVeCuzdanDogrulaRequestBody();
            inValue.Body.TCKimlikNo = TCKimlikNo;
            inValue.Body.Ad = Ad;
            inValue.Body.Soyad = Soyad;
            inValue.Body.SoyadYok = SoyadYok;
            inValue.Body.DogumGun = DogumGun;
            inValue.Body.DogumGunYok = DogumGunYok;
            inValue.Body.DogumAy = DogumAy;
            inValue.Body.DogumAyYok = DogumAyYok;
            inValue.Body.DogumYil = DogumYil;
            inValue.Body.CuzdanSeri = CuzdanSeri;
            inValue.Body.CuzdanNo = CuzdanNo;
            inValue.Body.TCKKSeriNo = TCKKSeriNo;
            return ((KPSPublicV2.KPSPublicV2Soap)(this)).KisiVeCuzdanDogrulaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.KPSPublicV2Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.KPSPublicV2Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.KPSPublicV2Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://tckimlik.nvi.gov.tr/Service/KPSPublicV2.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.KPSPublicV2Soap12))
            {
                return new System.ServiceModel.EndpointAddress("https://tckimlik.nvi.gov.tr/Service/KPSPublicV2.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            KPSPublicV2Soap,
            
            KPSPublicV2Soap12,
        }
    }
}
